name: deploy aws resources on infra

on:
  push:
    branches: ['infra']

env:
  AWS_REGION: ap-northeast-1

jobs:
  aws_cdk:
    defaults:
      run:
        working-directory: infra
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # - name: install npm
      #   run: 'sudo apt update -y && sudo apt install nodejs npm -y'

      # - name: install aws cdk
      #   run: 'sudo npm install -g aws-cdk'

      # - name: install requirements
      #   run: 'pip install -r requirements.txt'

      # - name: cdk diff
      #   run: cdk diff

      # - name: cdk synth
      #   run: cdk synth

      # - name: cdk deploy
      #   run: cdk deploy --require-approval never